# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lineage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlineage.proto\x12\x0eseigr_protocol\"s\n\x07Lineage\x12\x12\n\ncreator_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63urrent_hash\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12-\n\x07\x65ntries\x18\x04 \x03(\x0b\x32\x1c.seigr_protocol.LineageEntry\"\xf6\x01\n\x0cLineageEntry\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x12\n\ncreator_id\x18\x03 \x01(\t\x12\x16\n\x0e\x63ontributor_id\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\x12\x17\n\x0fprevious_hashes\x18\x06 \x03(\t\x12<\n\x08metadata\x18\x07 \x03(\x0b\x32*.seigr_protocol.LineageEntry.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lineage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LINEAGEENTRY_METADATAENTRY._options = None
  _LINEAGEENTRY_METADATAENTRY._serialized_options = b'8\001'
  _LINEAGE._serialized_start=33
  _LINEAGE._serialized_end=148
  _LINEAGEENTRY._serialized_start=151
  _LINEAGEENTRY._serialized_end=397
  _LINEAGEENTRY_METADATAENTRY._serialized_start=350
  _LINEAGEENTRY_METADATAENTRY._serialized_end=397
# @@protoc_insertion_point(module_scope)
