# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audit.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'audit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udit.proto\x12\x0bseigr.audit\"\xbc\x02\n\nAuditEntry\x12\x10\n\x08\x61udit_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0bresource_id\x18\x03 \x01(\t\x12,\n\x06\x61\x63tion\x18\x04 \x01(\x0e\x32\x1c.seigr.audit.AuditActionType\x12,\n\x08severity\x18\x05 \x01(\x0e\x32\x1a.seigr.audit.AuditSeverity\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x12\x0f\n\x07outcome\x18\x07 \x01(\t\x12\x37\n\x08metadata\x18\x08 \x03(\x0b\x32%.seigr.audit.AuditEntry.MetadataEntry\x12\x0c\n\x04hash\x18\t \x01(\t\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd8\x01\n\nAuditTrail\x12\x10\n\x08trail_id\x18\x01 \x01(\t\x12(\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x17.seigr.audit.AuditEntry\x12\x42\n\x0equery_metadata\x18\x03 \x03(\x0b\x32*.seigr.audit.AuditTrail.QueryMetadataEntry\x12\x14\n\x0cgenerated_at\x18\x04 \x01(\t\x1a\x34\n\x12QueryMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xc9\x01\n\x0b\x41uditConfig\x12\x16\n\x0eretention_days\x18\x01 \x01(\x05\x12\x15\n\rlogging_level\x18\x02 \x01(\t\x12 \n\x18\x65nable_hash_verification\x18\x03 \x01(\x08\x12\x38\n\x08metadata\x18\x04 \x03(\x0b\x32&.seigr.audit.AuditConfig.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*d\n\rAuditSeverity\x12\x1c\n\x18\x41UDIT_SEVERITY_UNDEFINED\x10\x00\x12\x0e\n\nAUDIT_INFO\x10\x01\x12\x11\n\rAUDIT_WARNING\x10\x02\x12\x12\n\x0e\x41UDIT_CRITICAL\x10\x03*\xc3\x01\n\x0f\x41uditActionType\x12\x1a\n\x16\x41UDIT_ACTION_UNDEFINED\x10\x00\x12\x17\n\x13\x41UDIT_ACTION_CREATE\x10\x01\x12\x17\n\x13\x41UDIT_ACTION_UPDATE\x10\x02\x12\x17\n\x13\x41UDIT_ACTION_DELETE\x10\x03\x12\x17\n\x13\x41UDIT_ACTION_ACCESS\x10\x04\x12\x17\n\x13\x41UDIT_ACTION_EXPORT\x10\x05\x12\x17\n\x13\x41UDIT_ACTION_IMPORT\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDITENTRY_METADATAENTRY']._loaded_options = None
  _globals['_AUDITENTRY_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_AUDITTRAIL_QUERYMETADATAENTRY']._loaded_options = None
  _globals['_AUDITTRAIL_QUERYMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_AUDITCONFIG_METADATAENTRY']._loaded_options = None
  _globals['_AUDITCONFIG_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_AUDITSEVERITY']._serialized_start=770
  _globals['_AUDITSEVERITY']._serialized_end=870
  _globals['_AUDITACTIONTYPE']._serialized_start=873
  _globals['_AUDITACTIONTYPE']._serialized_end=1068
  _globals['_AUDITENTRY']._serialized_start=29
  _globals['_AUDITENTRY']._serialized_end=345
  _globals['_AUDITENTRY_METADATAENTRY']._serialized_start=298
  _globals['_AUDITENTRY_METADATAENTRY']._serialized_end=345
  _globals['_AUDITTRAIL']._serialized_start=348
  _globals['_AUDITTRAIL']._serialized_end=564
  _globals['_AUDITTRAIL_QUERYMETADATAENTRY']._serialized_start=512
  _globals['_AUDITTRAIL_QUERYMETADATAENTRY']._serialized_end=564
  _globals['_AUDITCONFIG']._serialized_start=567
  _globals['_AUDITCONFIG']._serialized_end=768
  _globals['_AUDITCONFIG_METADATAENTRY']._serialized_start=298
  _globals['_AUDITCONFIG_METADATAENTRY']._serialized_end=345
# @@protoc_insertion_point(module_scope)
