name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Welcome to Seigr! Thank you for opening your first issue here. We appreciate your input, and our team will review it soon. Don't hesitate to join the discussions and explore ways to contribute!"
          pr-message: "🌱 Thank you for your first pull request! Your contribution brings us closer to a resilient, eco-driven future. Our team will review it shortly—excited to have you on board!"
